/* Shell (config.h)
 * A simple shell made in C++
 * Github: https://www.github.com/lewisevans2007/shell
 * Licence: GNU General Public License v3.0
 * By: Lewis Evans
 *
 * Shell configuration header file
 * DO NOT EDIT THIS FILE. Instead, use menuconfig to edit the configuration via
 * make menuconfig
 */

/* Shell version */
#define CONFIG_VERSION_MAJOR 1
#define CONFIG_VERSION_MINOR 4
#define CONFIG_VERSION_PATCH 2
#define CONFIG_VERSION_NAME "Beta"

/* Shell general */
#define CONFIG_NAME "Shell++"
#define CONFIG_WELCOME_MESSAGE true
#define CONFIG_CUSTOM_WELCOME_MESSAGE false
#define CONFIG_CUSTOM_WELCOME_MESSAGE_TEXT "Type 'help' for a list of commands"

/* Printsh */

/**
 * CONFIG_LOG_LEVEL - the log level
 * 0 - no logging
 * 1 - errors
 * 2 - errors and warnings
 * 3 - errors, warnings and info
 * 4 - errors, warnings, info and debug
 */
#define CONFIG_LOG_LEVEL 2

/**
 * CONFIG_PRINTSH_LOG_TO_FILE - whether to log to a file
 * CONFIG_PRINTSH_LOG_FILE_PATH - the path to the log file
 */
#define CONFIG_PRINTSH_LOG_TO_FILE false
#define CONFIG_PRINTSH_LOG_FILE_PATH "shell.log"

/* History */
#define CONFIG_HISTORY_FILE_PATH ".shell_history"
